INSERT INTO people (pfirst, plast, pstate, pcity) VALUES
 ('Bsqnbed', 'Qvrkx', 'ND', 'Chula Vista'),
 ('Wn', 'Kcuwhetnzwzj', 'VT', 'Santa Rosa'),
 ('Gvtsuj', 'Xlgv', 'CT', 'Newark'),
 ('Qbhbprneq', 'Gxnvka', 'SD', 'Huntington Beach'),
 ('Zdfk', 'Olvsxblpmh', 'DE', 'Las Vegas'),
 ('Wrl', 'Pkbkfzvhvztsr', 'WI', 'Mobile'),
 ('Rjvje', 'Xqyzgarrdmw', 'VA', 'Stockton'),
 ('Xiolyamdpqbht', 'Ogrhz', 'IL', 'Aurora'),
 ('Ifdqbpqo', 'Qovdcmpzywlrs', 'KS', 'Nashville-Davidson'),
 ('Rqvglof', 'Hjlhrgckfnyyg', 'MI', 'Albuquerque'),
 ('Xxrnfsgnbgvul', 'Juwdpoyyh', 'NJ', 'Reno'),
 ('Tgya', 'Ozzezkfx', 'MI', 'Seattle'),
 ('Gmebalqohjid', 'Dwimse', 'SC', 'Akron'),
 ('Wilmbzuh', 'Hdrsj', 'ID', 'Charlotte'),
 ('Fvhgtej', 'Fngvgohtyrrgd', 'WV', 'Moreno Valley'),
 ('Mj', 'Btlrpezghvzc', 'SD', 'Richmond'),
 ('Yeftmzagdoq', 'Fmv', 'WA', 'Little Rock'),
 ('Ue', 'Fn', 'IN', 'Garden Grove'),
 ('Cc', 'Sq', 'VI', 'Port St. Lucie'),
 ('Fp', 'Tgiembpzxlj', 'RI', 'Boise City'),
 ('Sohkwhe', 'Pilbqlbxlxhq', 'ME', 'Irvine'),
 ('Xtmytccsrl', 'Chwult', 'FM', 'Portland'),
 ('Vny', 'Qv', 'IA', 'Oxnard'),
 ('Saehx', 'Rqpcvaumkzgg', 'MD', 'Miami'),
 ('Oqipbeajj', 'Wdquuxfdux', 'WA', 'Stockton'),
 ('Skhrfihwmxka', 'Csheta', 'NH', 'Tulsa'),
 ('Zvdvbldacdqxt', 'Oleectm', 'KY', 'Huntington Beach'),
 ('Iqkaplfj', 'Slroxnax', 'MH', 'Madison'),
 ('Qoxs', 'Dtngqay', 'PW', 'Mobile'),
 ('Xoze', 'Ogpkqmbcilta', 'DC', 'Madison'),
 ('Lkldjkzucn', 'Ifksci', 'MO', 'Newark'),
 ('Xs', 'Okpyajorsoqoc', 'AZ', 'Augusta-Richmond County'),
 ('Nsdhk', 'Gjessppzojus', 'OR', 'Columbus'),
 ('Ufsqmzcdnb', 'Ji', 'VI', 'Modesto'),
 ('Oicvhhp', 'Nbrzhmjbbp', 'OK', 'Rancho Cucamonga'),
 ('Xcuiijvzm', 'Troo', 'OH', 'Little Rock'),
 ('Hmkaynzg', 'Dzcvgospiit', 'AK', 'Little Rock'),
 ('Aw', 'Nevmgyleq', 'TX', 'Des Moines'),
 ('Fcfhmds', 'Sofhudok', 'PR', 'Fort Lauderdale'),
 ('Gv', 'Zvndynt', 'VI', 'Columbus'),
 ('Xkvrky', 'Jaaq', 'OR', 'Norfolk'),
 ('Xointdpwgohro', 'Wjjftmok', 'PR', 'Scottsdale'),
 ('Vypsdrepxwmjc', 'Wiefni', 'MT', 'Buffalo'),
 ('Dnnsffn', 'Fncoyhc', 'CT', 'Garden Grove'),
 ('Zed', 'Szwzx', 'CT', 'Jacksonville'),
 ('Enq', 'Yfovbtrcllaxq', 'AR', 'Santa Ana'),
 ('Vkpnzrz', 'Womwmlydhbbu', 'ND', 'Albuquerque'),
 ('Rmnzzzgcss', 'Suluzjysrkda', 'ND', 'Ontario'),
 ('Czocuik', 'Egub', 'AS', 'Arlington'),
 ('Gmgxcbxzjn', 'Hjezu', 'OH', 'Vancouver'),
 ('Cyeqkhpiuhaw', 'Xfxmzg', 'OH', 'Worcester'),
 ('Sjqgvek', 'Osndzccqgqts', 'NM', 'Cleveland'),
 ('Jfnfocijwphri', 'Hqfbokicyugh', 'VT', 'El Paso'),
 ('Qc', 'Cnfz', 'OH', 'Mesa'),
 ('Toiyfum', 'Zmkh', 'MD', 'Yonkers'),
 ('Cnsq', 'Esfzn', 'NC', 'Richmond'),
 ('Zlrp', 'Ssnyind', 'SC', 'Los Angeles'),
 ('Fvms', 'Tleagdxq', 'LA', 'Fort Worth'),
 ('Xafvln', 'Astjq', 'MA', 'Oklahoma City'),
 ('Ex', 'Vqoidev', 'OR', 'Salt Lake City'),
 ('Wrwqqqmpzbu', 'Wsmq', 'IN', 'Atlanta'),
 ('Jlmdopuhahaee', 'Watszkdus', 'NJ', 'Houston'),
 ('Jpohgadutnjjk', 'Jybwfwmnvmey', 'SC', 'Cape Coral'),
 ('Xxzfnexdihpp', 'Uwmszpnatrrx', 'PR', 'Madison'),
 ('Jil', 'Fxhkjqxovkxr', 'AK', 'Denver'),
 ('Xzzv', 'Rmfnww', 'NH', 'Austin'),
 ('Hukjimd', 'Mvqrviqwlwf', 'WI', 'Fayetteville'),
 ('Szsmjd', 'Ufaxolbpw', 'DC', 'Reno'),
 ('Dbydqedrpfndr', 'Zpzxzjgw', 'OR', 'Denver'),
 ('Kndxuxmpgqtck', 'Dtihxckew', 'PW', 'Tacoma'),
 ('Zwbzlnqwltvvw', 'Nsdojyyem', 'OK', 'Memphis'),
 ('Qc', 'Fdcsinzbgv', 'WV', 'St. Petersburg'),
 ('Rntnpgkb', 'Cpkyt', 'KS', 'Jersey City'),
 ('Xdntwcol', 'Nux', 'FM', 'Fontana'),
 ('Euk', 'Yriy', 'MT', 'Worcester'),
 ('Qyhgchzeji', 'Gfmumigdghdpp', 'OR', 'Brownsville'),
 ('Erqyqzleywsp', 'Auqywohlataf', 'OR', 'Cape Coral'),
 ('Yyzsbsk', 'Oz', 'AR', 'Columbus'),
 ('Yiqljspqhj', 'Qbwstjazbo', 'NV', 'Nashville-Davidson'),
 ('Kedfsz', 'Scqnoedey', 'UT', 'Irvine'),
 ('Unhs', 'Gtwzmbfvmvmrk', 'OK', 'San Diego'),
 ('Lde', 'Pciwp', 'DC', 'Philadelphia'),
 ('Tlxw', 'Xeg', 'SC', 'Fort Worth'),
 ('Uymvpptqdxq', 'Ityngzrmnmqz', 'IA', 'Los Angeles'),
 ('Ao', 'Fshkf', 'ME', 'Indianapolis'),
 ('Vzpiumzpdbz', 'Jr', 'NH', 'Charlotte'),
 ('Wo', 'Wcdi', 'GU', 'Santa Ana'),
 ('Aadeqzofx', 'Zohbkek', 'WY', 'Fort Wayne'),
 ('Kfsipsdcvm', 'Baad', 'KY', 'Oxnard'),
 ('Diywdksa', 'Pkgbqdiabzlyv', 'NH', 'Fort Worth'),
 ('Ljaei', 'Mmbkrklgpnlu', 'PW', 'Los Angeles'),
 ('Tvs', 'Qiinduedkbdzf', 'AZ', 'Oceanside'),
 ('Hbikx', 'Slcdnkiht', 'AS', 'Boston'),
 ('Waul', 'Jlut', 'WY', 'Minneapolis'),
 ('Iqvgfvqbn', 'Cjbdypyq', 'GU', 'Birmingham'),
 ('Mupmv', 'Ff', 'UT', 'Colorado Springs'),
 ('Gkeioq', 'Mzox', 'WA', 'Richmond'),
 ('Dpwmvvudikn', 'Qijkouluvm', 'GA', 'Atlanta'),
 ('Azpduuszbef', 'Ucmyn', 'NM', 'Atlanta'),
 ('Wejs', 'Pjjrgm', 'IL', 'Washington'),
 ('Nolcw', 'Inwsfwrdqhu', 'PR', 'Shreveport'),
 ('Hzhanumoed', 'Dxhn', 'KY', 'El Paso'),
 ('Ee', 'Zxoovxvoppqye', 'VA', 'Overland Park'),
 ('Swrerqmieaose', 'Txgvtfakfja', 'KY', 'New York'),
 ('Etpd', 'Cudbscxyj', 'AS', 'San Francisco'),
 ('Bhtvykyboc', 'Zxvszokdtpm', 'KY', 'Philadelphia'),
 ('Ysowrxwoa', 'Qbmdl', 'RI', 'Jackson'),
 ('Retglrp', 'Jougiiuexfi', 'TX', 'New York'),
 ('Gqwm', 'Atl', 'CO', 'Oakland'),
 ('Cccocpvir', 'Xhmnikys', 'GU', 'Shreveport'),
 ('Ndoejnrlo', 'Bnmgxctv', 'NC', 'Portland'),
 ('Fyzdur', 'Bnh', 'VT', 'Tallahassee'),
 ('Vuqcclzmv', 'Bmrqvhxyljpe', 'ME', 'Irving'),
 ('Rssq', 'Oxeis', 'ID', 'Milwaukee'),
 ('Qai', 'Eotquzzzzlumm', 'IA', 'Lexington-Fayette'),
 ('Xu', 'Xgvmzsqjqecj', 'KS', 'Miami'),
 ('Chjbdqfh', 'Kfwhcdcrdlu', 'MD', 'Indianapolis'),
 ('Gkjxypmatp', 'Xbtsvk', 'NV', 'Greensboro'),
 ('Kv', 'Dadbhccwhfx', 'OR', 'Tampa'),
 ('Xdnvougfuuos', 'Nvodergxuzawx', 'FM', 'Long Beach'),
 ('Uc', 'Utj', 'MP', 'Phoenix'),
 ('Yzmuoefjg', 'Zu', 'PR', 'Houston'),
 ('Mtpj', 'Llqytdheofquk', 'AR', 'Des Moines'),
 ('Yeqhwcmec', 'Yigidser', 'DE', 'Cape Coral'),
 ('Ampxyqiv', 'Hzriomy', 'AK', 'Aurora'),
 ('Axpqe', 'Mtod', 'FM', 'Rochester'),
 ('Oqle', 'Npzj', 'PR', 'Laredo'),
 ('Jgs', 'Bxxlzerhxzvl', 'PA', 'Columbus'),
 ('Aexpkb', 'Zztital', 'AR', 'Des Moines'),
 ('Pzpaidsf', 'Uvejyjvf', 'CT', 'Sacramento'),
 ('Mohubka', 'Nqkhjydxhgg', 'DE', 'Columbus'),
 ('Gc', 'Xlgcum', 'ND', 'Louisville/Jefferson County'),
 ('Ipwos', 'Jza', 'GU', 'New Orleans'),
 ('Uinedcqhrmzb', 'Yqtvbdkdpcqs', 'AR', 'Dallas'),
 ('Dpmslmezt', 'Iciklrwcne', 'FL', 'Lincoln'),
 ('Cdruw', 'Elaxdgainqgba', 'VT', 'Knoxville'),
 ('Bqr', 'Uhfgczsgsnt', 'NV', 'Denver'),
 ('Guyrp', 'Sxgznfqshbs', 'SC', 'Seattle'),
 ('Bkxdpjmc', 'Sq', 'PA', 'Lexington-Fayette'),
 ('Fgye', 'Vpr', 'WV', 'Boise City'),
 ('Ueexxfrvtxm', 'Fmqzhczlneiuz', 'RI', 'Overland Park'),
 ('Tixvbel', 'Nzreac', 'IA', 'Anchorage'),
 ('Mrpntvvonmds', 'Xkq', 'NJ', 'Virginia Beach'),
 ('Sisyw', 'Xdoxxmyoc', 'RI', 'Miami'),
 ('Djbfnmklovf', 'Pybdnzpw', 'VI', 'Colorado Springs'),
 ('Qqxcpnskrunl', 'Rvnhgkniugj', 'PW', 'Yonkers'),
 ('Rcjpqid', 'Zfdrjdgmps', 'FL', 'Albuquerque'),
 ('Sxc', 'Yediiodu', 'PA', 'Richmond'),
 ('Xor', 'Jvjyksbw', 'CA', 'Cincinnati'),
 ('Phywbqyfpj', 'Ova', 'NC', 'Irving'),
 ('Cefwgc', 'Zqsnudypbjjf', 'KY', 'San Francisco'),
 ('Xlb', 'Mgmxwxfih', 'DE', 'Lincoln'),
 ('Kcfmipqgccu', 'Vy', 'OK', 'Aurora'),
 ('Zseditscbi', 'Wypsk', 'NC', 'Los Angeles'),
 ('Mogtg', 'Stozkuyz', 'CT', 'Memphis'),
 ('Aetlmlgh', 'Zk', 'MP', 'Tallahassee'),
 ('Hwvtsowiaamn', 'Skvhninoaccqn', 'MS', 'Gilbert'),
 ('Lpsbwe', 'Ologlnqti', 'UT', 'Arlington'),
 ('Kydtqya', 'Rygwomvqk', 'VI', 'Louisville/Jefferson County'),
 ('Ruaf', 'Xihzqifqsznq', 'PR', 'Miami'),
 ('Oigkirphwy', 'Phdyqamwlubbw', 'SD', 'Jacksonville'),
 ('Jxcj', 'Fj', 'DC', 'Columbus'),
 ('Leqy', 'Ylf', 'NV', 'Montgomery'),
 ('Guzee', 'Rdqpndcryfgx', 'MI', 'Bakersfield'),
 ('Oxztuqwoiodsj', 'Aymolsw', 'KS', 'Long Beach'),
 ('Tnep', 'Lsdaqrozpya', 'MT', 'San Francisco'),
 ('Kh', 'Zv', 'MI', 'San Antonio'),
 ('Regtdmxjsvys', 'Ixfe', 'NM', 'St. Petersburg'),
 ('Bulpynxzwnulg', 'Akpzpptl', 'OR', 'Detroit'),
 ('Ncocdpyyizf', 'Mjyf', 'MP', 'St. Louis'),
 ('Zzovrtatmp', 'Ypdldixhq', 'WI', 'Atlanta'),
 ('Rz', 'Hgvnhwxawjrjf', 'NC', 'Minneapolis'),
 ('Uc', 'Kkzxwmicm', 'AR', 'Glendale'),
 ('Espwmncehz', 'Lwwcjjrv', 'SD', 'Shreveport'),
 ('Dbnh', 'Cvuehb', 'MT', 'San Bernardino'),
 ('Ijyzvudnmrwpn', 'Kpbhfbcgywln', 'DE', 'Moreno Valley'),
 ('On', 'Snkdypvqaiw', 'IN', 'Tulsa'),
 ('Pryglxebsw', 'Egmrnplwyn', 'GU', 'Glendale'),
 ('Tf', 'Aw', 'TN', 'Raleigh'),
 ('Odq', 'Sugoyehlh', 'AR', 'Irving'),
 ('Mwjly', 'Rvxyurabzsy', 'WI', 'Orlando'),
 ('Nqnddgvuwi', 'Myxartwcfb', 'ID', 'Orlando'),
 ('Pxwtcwxgn', 'Bybaslaxxlfq', 'AK', 'Worcester'),
 ('Blqoxvohoc', 'Rijiv', 'AK', 'Huntsville'),
 ('Xzwqtq', 'Gxjrwshst', 'MN', 'Salt Lake City'),
 ('Xlnyx', 'Tdfjknhqsee', 'CO', 'Tulsa'),
 ('Moblwiux', 'Hvox', 'IA', 'Fontana'),
 ('Geedkuyzbrw', 'Hxex', 'MH', 'Milwaukee'),
 ('Jmnska', 'Peanup', 'NY', 'Oxnard'),
 ('Scmwd', 'Jpdtflggv', 'NH', 'Amarillo'),
 ('Rde', 'Ywxeetobezk', 'AL', 'San Jose'),
 ('Luj', 'Qfnuslaicdw', 'NH', 'Miami'),
 ('Uxekuquevgddx', 'Qbxwgwbk', 'MN', 'Norfolk'),
 ('Shm', 'Ymqlan', 'OK', 'Tucson'),
 ('Kokxdzjaee', 'Dclyu', 'ND', 'Winston-Salem'),
 ('Uf', 'Neftiugabvpn', 'NE', 'Denver'),
 ('Znqmatj', 'Xtbgwspll', 'MP', 'Laredo'),
 ('Uvvqwawirp', 'Gcepsjrghhar', 'AZ', 'North Las Vegas'),
 ('Ddybz', 'Kwkxgjrqd', 'OR', 'Jackson'),
 ('Xcxk', 'Vxgoyzlawoop', 'MO', 'San Diego'),
 ('Ywqivak', 'Nme', 'PW', 'Aurora'),
 ('Ljwcqvwgrlroh', 'Vjwpwtnxb', 'PR', 'Overland Park'),
 ('Wqacnwlacvnx', 'Bvdxefjrzntpo', 'FM', 'Irvine'),
 ('Ojfk', 'Fanzq', 'MH', 'Tacoma'),
 ('Lwr', 'Lndysoooh', 'IA', 'Aurora'),
 ('Hour', 'Nqmqphhkoows', 'IN', 'Cleveland'),
 ('Ysi', 'Fpdevi', 'VI', 'Baton Rouge'),
 ('Qemqxqdh', 'Mnshlnwqk', 'WV', 'Glendale'),
 ('Yfcknckqcud', 'Bvfvty', 'TX', 'Tucson'),
 ('Zrgapibnpui', 'Azpjyzghfa', 'SC', 'Fremont'),
 ('Tmwcimff', 'Zeaeixbskwp', 'PW', 'San Bernardino'),
 ('Kympjlahkbkrr', 'Aqqpf', 'NC', 'Oxnard'),
 ('Gvqffpdrbet', 'Elsrwvluvow', 'FL', 'Newark'),
 ('Qme', 'Ao', 'CO', 'Cincinnati'),
 ('Zyggxxwfme', 'Uahfmkvdax', 'GU', 'Omaha'),
 ('Bo', 'Wse', 'ID', 'Irvine'),
 ('Tphhywvpgdv', 'Ljl', 'TN', 'Laredo'),
 ('Qkk', 'Cnuljtbvyiww', 'TN', 'Laredo'),
 ('Ihwuziol', 'Tgs', 'OK', 'Vancouver'),
 ('Dipp', 'Lropobpwk', 'ID', 'Anchorage'),
 ('Ca', 'Mmf', 'SD', 'Worcester'),
 ('Hihkhci', 'Zksumugy', 'TX', 'Raleigh'),
 ('Vgrjtsuoijm', 'Xdzylzsmk', 'HI', 'North Las Vegas'),
 ('Cvmlzv', 'Tvbabzabldx', 'MA', 'Norfolk'),
 ('Gjbgmdcnxr', 'Egowpjmjsokxd', 'FM', 'Cape Coral'),
 ('Khq', 'Cqm', 'AR', 'Chandler'),
 ('Uzdioeq', 'Mybdohjowxnvw', 'HI', 'Chattanooga'),
 ('Zsjrfujgyrow', 'Haxqppyutn', 'TX', 'Santa Rosa'),
 ('Xpwjzlqmdhfqp', 'Nbemxxxhdj', 'WI', 'Washington'),
 ('Ougd', 'Slgokbuypk', 'ID', 'Cincinnati'),
 ('Wshdthyba', 'Hlk', 'MS', 'Rochester'),
 ('Vhbvy', 'Nsdtqbh', 'MT', 'Riverside'),
 ('Dwhfwrvxsflrv', 'Xgczzpgfm', 'WI', 'Jacksonville'),
 ('Si', 'Tnn', 'RI', 'Chula Vista'),
 ('Bqdviacxwf', 'Goprukr', 'OH', 'Laredo'),
 ('Rjq', 'Ixfr', 'IN', 'Montgomery'),
 ('Klmhotffsjsc', 'Gohduckl', 'MS', 'Glendale'),
 ('Cyjgfoq', 'Ilopjvtgmwar', 'MH', 'Chandler'),
 ('Hjig', 'Urx', 'IN', 'Tallahassee'),
 ('Ie', 'Bqz', 'TN', 'San Bernardino'),
 ('Hmjzapzxmozgh', 'Nbsbthow', 'CA', 'Tallahassee'),
 ('Fgrrzhewbxj', 'Hec', 'MS', 'Los Angeles'),
 ('Wkrpdqpc', 'Oyllqww', 'NC', 'St. Paul'),
 ('Epaketooxu', 'Hqivlczng', 'ID', 'Jacksonville'),
 ('Ujjy', 'Sgvojqthchsrx', 'NE', 'Colorado Springs'),
 ('Dyydk', 'Trtwzt', 'UT', 'Boston'),
 ('Bns', 'Skedojhen', 'NV', 'Spokane'),
 ('Fgasmtdsrzzk', 'Cqi', 'WY', 'Fort Lauderdale'),
 ('Jyqxwl', 'Fhoqxixxn', 'AR', 'Arlington'),
 ('Wgrbonlycry', 'Blwaoj', 'FL', 'Anchorage'),
 ('Hpdgutygro', 'Gmschjz', 'CO', 'Cleveland'),
 ('Oclw', 'Vf', 'MT', 'Spokane'),
 ('Bzktv', 'Mctvlbybwm', 'MA', 'Fayetteville'),
 ('Ufkb', 'Xijtbacqxxke', 'NJ', 'Nashville-Davidson'),
 ('Gm', 'Rhlvqbnxf', 'KY', 'Amarillo'),
 ('Mhntqus', 'Ooehmlzwkij', 'FM', 'Chicago'),
 ('Vjtxsh', 'Tilbznjiltjxd', 'MT', 'Ontario'),
 ('Lvfhjvyvi', 'Ckalvhdg', 'MP', 'Minneapolis'),
 ('Qnea', 'Pjvkjoktvme', 'FL', 'El Paso'),
 ('Kvg', 'Gwrjwrbiowovn', 'MN', 'New Orleans'),
 ('Jkoa', 'Cvvluraouep', 'CT', 'Huntington Beach'),
 ('Osv', 'Zukeemt', 'VI', 'Richmond'),
 ('Jhletnrdeo', 'Eghxhx', 'VI', 'St. Paul'),
 ('Clfqeqb', 'Sahvlaakdwm', 'ME', 'Raleigh'),
 ('Lmogngtword', 'Xpf', 'MD', 'Vancouver'),
 ('Efgxqzggz', 'Roeafd', 'HI', 'Huntington Beach'),
 ('Pvm', 'Ejimxrwlox', 'ND', 'Yonkers'),
 ('Kokccvc', 'Ihag', 'TN', 'Vancouver'),
 ('Mhrhijzhtnw', 'Gpbryhfg', 'WA', 'Albuquerque'),
 ('Ra', 'Rnug', 'WI', 'Spokane'),
 ('Zihyshmdtse', 'Re', 'DC', 'Louisville/Jefferson County'),
 ('Efwltafixsoa', 'Bwwliipkgzi', 'IN', 'Pittsburgh'),
 ('Rrokcdxfpxp', 'Muchvkir', 'NC', 'Fremont'),
 ('Ptzefwr', 'Xh', 'ID', 'Fremont'),
 ('Yeyolnmfyqg', 'Ehfczjzlgatq', 'KS', 'Greensboro'),
 ('Srgkkwolitdn', 'Swifa', 'OK', 'El Paso'),
 ('Hd', 'Vezfab', 'GA', 'Riverside'),
 ('Xnmfzot', 'Bsqg', 'GU', 'Chattanooga'),
 ('Ekktg', 'Figzfkhqwjqs', 'MD', 'Orlando'),
 ('Lgzycj', 'Ziujtaxf', 'MN', 'Worcester'),
 ('Dxrztmaetcz', 'Jwzkecpgfzf', 'DE', 'Portland'),
 ('Vqkupxnnvbw', 'Gfhophlmvzxod', 'ND', 'Buffalo'),
 ('Mbf', 'Sjgyigh', 'MS', 'Anaheim'),
 ('Ad', 'Nm', 'OH', 'San Diego'),
 ('Gqambdu', 'Mfzevfko', 'MA', 'San Francisco'),
 ('Xa', 'Jmixn', 'SC', 'Vancouver'),
 ('Rdfywjs', 'Mc', 'IL', 'Overland Park'),
 ('Cqjgiubhitw', 'Ehfverxk', 'MI', 'Tallahassee'),
 ('Axurlg', 'Oyoubgc', 'MT', 'Birmingham'),
 ('Tzizooaq', 'Bzk', 'MS', 'Charlotte'),
 ('Ezwwspjpqa', 'Cxdgyid', 'VA', 'Jacksonville'),
 ('Rhfxyxtvlxztv', 'Lssdxwui', 'OK', 'El Paso'),
 ('Wizjn', 'Pmg', 'NJ', 'Spokane'),
 ('Xtgdvgwx', 'Mbxs', 'PW', 'Baltimore'),
 ('Mgxjkqjaavwbg', 'Eogduaur', 'MH', 'Nashville-Davidson'),
 ('Wni', 'Ac', 'AK', 'Oxnard'),
 ('Mxdjstk', 'Nx', 'ND', 'Vancouver'),
 ('Ipjjemwwph', 'Jkjadstxw', 'MD', 'Tallahassee'),
 ('Jmqagcwdedj', 'Nyjy', 'MT', 'Moreno Valley'),
 ('Gxfzhgeqxgaz', 'Fftlniedcmts', 'AS', 'Colorado Springs'),
 ('Docbfglhrhqxn', 'Krpqesdq', 'AZ', 'Boise City'),
 ('Rkihlyibjpi', 'Umexzkzycamax', 'OR', 'Arlington'),
 ('Axmdifvlgp', 'Eeaskcztwz', 'MA', 'Albuquerque'),
 ('Rnajtpi', 'Hyruymjkvl', 'VT', 'Las Vegas'),
 ('Gkkuqvuczfu', 'Fckh', 'LA', 'Omaha'),
 ('Kwya', 'Drrucoupzzaa', 'GA', 'Cincinnati'),
 ('Ebnedog', 'Rxkdnxnvuxo', 'AZ', 'Garden Grove'),
 ('Ugfxku', 'Mlyg', 'CO', 'Madison'),
 ('Ehkcxfucyu', 'Fvdojmzedz', 'HI', 'Stockton'),
 ('Agdnysma', 'Dmldhxhyv', 'PR', 'Augusta-Richmond County'),
 ('Ojlapacpl', 'Uk', 'IA', 'Portland'),
 ('Aoylks', 'Uqdpefqtbmzj', 'DE', 'Oxnard'),
 ('Wypjkirv', 'Jctwqlzkeabs', 'RI', 'Salt Lake City'),
 ('Pnzrgowux', 'Onvvio', 'NE', 'Orlando'),
 ('Xp', 'Qswt', 'KY', 'Nashville-Davidson'),
 ('Vzxsfk', 'Ekhltonbnu', 'IA', 'Lincoln'),
 ('Nhd', 'Hc', 'AK', 'Garland'),
 ('Df', 'Dzn', 'MA', 'Minneapolis'),
 ('Rgqgxmxul', 'Wqbu', 'CO', 'Grand Prairie'),
 ('Xruq', 'Xtxcdo', 'MH', 'Glendale'),
 ('Avzqffud', 'Eeyswmwoke', 'WY', 'Hialeah'),
 ('Ajq', 'Jzpoelsh', 'FM', 'St. Paul'),
 ('Qun', 'Oucuzm', 'GA', 'Mesa'),
 ('Cnkvidmztln', 'Riwfirud', 'NJ', 'New York'),
 ('Ntou', 'Shaeznnkj', 'AZ', 'Jackson'),
 ('Cydjuazwnvdrl', 'Iatbeq', 'CO', 'Las Vegas'),
 ('Lvgxlhmeqi', 'Wsrgvgtvohm', 'GA', 'Raleigh'),
 ('Ceomswbxbwpy', 'Qtbszfrjzuu', 'NE', 'Tulsa'),
 ('Yxht', 'Ubks', 'CA', 'Lexington-Fayette'),
 ('Updtnbga', 'Qdx', 'MD', 'Tampa'),
 ('Sskedarw', 'Yzzdbhyldl', 'MH', 'Toledo'),
 ('Qyw', 'Obda', 'IL', 'San Bernardino'),
 ('Cyax', 'Fdrfnuoig', 'AS', 'Columbus'),
 ('Epdaofdmpy', 'Qim', 'WI', 'Santa Ana'),
 ('Jpd', 'Xncozpuaxda', 'PR', 'Chattanooga'),
 ('Tfunisfy', 'Zxc', 'WI', 'Baton Rouge'),
 ('Qovhlkambkm', 'Wslumkb', 'GU', 'Grand Prairie'),
 ('Cdbm', 'Kugzxaz', 'SC', 'Worcester'),
 ('Zjpcihwkeapxw', 'Qrnzen', 'WA', 'Oxnard'),
 ('Luvt', 'Bfahp', 'CT', 'Laredo'),
 ('Xtbeoa', 'Jmm', 'VA', 'Irvine'),
 ('Dhyuoysouhq', 'Uomqmlv', 'SD', 'Augusta-Richmond County'),
 ('Xp', 'Zfyjjcoqazz', 'NH', 'Baton Rouge'),
 ('Qjp', 'Wcdfcsvglghrj', 'TX', 'Huntington Beach'),
 ('Jjbotuvze', 'Ejtisuu', 'AZ', 'Lexington-Fayette'),
 ('Lbc', 'Anugqewxkw', 'GA', 'Memphis'),
 ('Ffrwd', 'Avwgfifhjgp', 'TN', 'Tucson'),
 ('Mvewukb', 'Xhhjhwzfwh', 'MP', 'Albuquerque'),
 ('Djboduykzne', 'Rlghqdmwf', 'NY', 'Cleveland'),
 ('Ozkzllj', 'Booivvbc', 'WA', 'Orlando'),
 ('Sjcqt', 'Pgdz', 'AL', 'Phoenix'),
 ('Bzd', 'Cx', 'TN', 'Jersey City'),
 ('Tbjw', 'Kbvfxspdsyw', 'NH', 'Grand Rapids'),
 ('Alo', 'Zsbbhrj', 'MH', 'St. Paul'),
 ('Tbyuwmrdcruv', 'Xs', 'IA', 'Sacramento'),
 ('Vrrqh', 'Jimiiqkjg', 'TN', 'Fayetteville'),
 ('Dwailcj', 'Ubgf', 'MS', 'Oceanside'),
 ('Ohcavmqpdijl', 'Ogjwvdl', 'GU', 'Pittsburgh'),
 ('Uuydyajcr', 'Jbvga', 'MA', 'Tucson'),
 ('Hf', 'Rxsubiuamgxv', 'AR', 'Garden Grove'),
 ('Ffdjxjcuyve', 'Idbmsdjfqydf', 'MA', 'Irving'),
 ('Se', 'Btofkbz', 'MD', 'Colorado Springs'),
 ('Xz', 'Kgpjfrlzpts', 'MT', 'Fort Worth'),
 ('Rfaecslws', 'Koklei', 'FL', 'Henderson'),
 ('Vlwknswkieprd', 'Ginqxw', 'SC', 'Anaheim'),
 ('Ofc', 'Eiqjpsobrsuu', 'AL', 'Dallas'),
 ('Bt', 'Kgowqdup', 'ID', 'Tampa'),
 ('Plqjvnpm', 'Vabnb', 'MN', 'Riverside'),
 ('Eaqxwtyein', 'Qzcophpdnxdzv', 'MI', 'Chandler'),
 ('Pjjzygudtsi', 'Egufdunu', 'MS', 'Philadelphia'),
 ('Gzobywrpub', 'Mngizxgkcj', 'FM', 'Rochester'),
 ('Xgiueyxvcsgf', 'Uos', 'IA', 'Nashville-Davidson'),
 ('Gmjinogu', 'Bqxiaq', 'KS', 'Aurora'),
 ('Apgrtxafsj', 'Psxzsvovnpfm', 'AZ', 'Spokane'),
 ('Vbrs', 'Uhhp', 'OH', 'Port St. Lucie'),
 ('Latuerqkj', 'Jcdzmj', 'NV', 'Garland'),
 ('Qm', 'Qawagmowmwojl', 'HI', 'St. Petersburg'),
 ('Hs', 'Ddzoopktheor', 'AR', 'Arlington'),
 ('Qglilxl', 'Tclip', 'MT', 'Plano'),
 ('Qpantseucgu', 'Jov', 'RI', 'Fresno'),
 ('Sdnyuiiqreth', 'Sindqvqycrjxp', 'MT', 'Aurora'),
 ('Carfeep', 'Hxgmqspdg', 'PA', 'Omaha'),
 ('Sldwtpocm', 'Wuvmkozuweypk', 'NH', 'Charlotte'),
 ('Pbggmv', 'Qtozhrbrrm', 'AZ', 'Henderson'),
 ('Oav', 'Bpjmmdo', 'KS', 'Philadelphia'),
 ('Cmsbw', 'Nfv', 'KS', 'St. Paul'),
 ('Mnnionedbbu', 'Rc', 'NE', 'Tallahassee'),
 ('Nsmxspudl', 'Zezlvmls', 'AZ', 'Omaha'),
 ('Ki', 'Swke', 'GA', 'Vancouver'),
 ('Qjhhfb', 'Rfnc', 'WI', 'Santa Ana'),
 ('Fxuzeuapb', 'Sgygpvoyn', 'VA', 'Pittsburgh'),
 ('Ostdqhpks', 'Kctzssndi', 'IL', 'Akron'),
 ('Mltucnfbmxv', 'He', 'AR', 'Chandler'),
 ('Qxtzznddmojsy', 'Uruohjwdwabu', 'WA', 'Tucson'),
 ('Uqhpzkpslrsa', 'Cxaquf', 'AK', 'North Las Vegas'),
 ('Ouvcsmemjvv', 'Jhy', 'ND', 'Shreveport'),
 ('Lns', 'Lvpbvyuwhikd', 'ID', 'Indianapolis'),
 ('Rrjgrsvyimnnb', 'Emjlowyncnhdl', 'AL', 'Miami'),
 ('Uh', 'Yfstbnl', 'ND', 'Grand Rapids'),
 ('Suqbjlvqdbrb', 'Miutix', 'RI', 'Las Vegas'),
 ('Rqomzgxptgjx', 'Gspcty', 'MN', 'Port St. Lucie'),
 ('Nvdfyc', 'Joy', 'NH', 'Santa Ana'),
 ('Vibzhnpa', 'Nnss', 'AK', 'Santa Clarita'),
 ('Xpifipexw', 'Oweam', 'GU', 'Tulsa'),
 ('Hmt', 'Snogpogjqv', 'WA', 'Yonkers'),
 ('Am', 'Zovr', 'DC', 'Amarillo'),
 ('Ufyykxluzyc', 'Ij', 'UT', 'Oakland'),
 ('Qo', 'Vvvacanud', 'WI', 'Glendale'),
 ('Wfswcg', 'Aagnzknpdyxz', 'WY', 'Providence'),
 ('Ffelvpf', 'Anmwiypgksss', 'FL', 'Oceanside'),
 ('Qnsdkz', 'Isijd', 'HI', 'Fort Wayne'),
 ('Mrrytaxevp', 'Qz', 'PA', 'Vancouver'),
 ('Oubwkv', 'Khqphrcgu', 'NM', 'Overland Park'),
 ('Fsbtmufdpamli', 'Xcjq', 'ID', 'Chicago'),
 ('Zsdsvpxi', 'Ihswv', 'PW', 'Greensboro'),
 ('Wyrezwglupbie', 'Qixn', 'WI', 'Glendale'),
 ('Uvsvjzwoqr', 'Man', 'NM', 'Chesapeake'),
 ('Puzvhexkxjlr', 'Vcsruzh', 'NE', 'Yonkers'),
 ('Pakfnb', 'Rfkk', 'FL', 'Amarillo'),
 ('Tgrcotsgxwfo', 'Aelza', 'NH', 'Cleveland'),
 ('Rkgmywdikgol', 'Qdtgipudgsps', 'CO', 'Modesto'),
 ('Nj', 'Eydwdjzhwh', 'NH', 'Garden Grove'),
 ('Aplcdoxxrgaxb', 'Fw', 'IA', 'Richmond'),
 ('Gdgxbqq', 'Qaqnqwk', 'AR', 'Milwaukee'),
 ('Rfnxfndao', 'Xnrpiniicdbry', 'PR', 'Rancho Cucamonga'),
 ('Jnbczpkrxjm', 'Cry', 'NE', 'Spokane'),
 ('Uydoirrhxrnpb', 'Jrckha', 'AZ', 'Riverside'),
 ('Pjhk', 'Jgxzm', 'AK', 'Sacramento'),
 ('Bbkfoixilspnx', 'Vkticpcemhng', 'MN', 'Corpus Christi'),
 ('Yl', 'Gcluhlbehvqum', 'MN', 'Plano'),
 ('Ugzwjmj', 'Pwm', 'MI', 'Durham'),
 ('Kwj', 'Vp', 'ME', 'Aurora'),
 ('Dndojygbls', 'Xabffpbqdktt', 'VA', 'Pittsburgh'),
 ('Loj', 'Lvyq', 'SC', 'Grand Rapids'),
 ('Ggm', 'Opmkahoxkpyoa', 'WI', 'Laredo'),
 ('Pxfx', 'Tiimup', 'DE', 'Baton Rouge'),
 ('Ck', 'Ta', 'GA', 'Madison'),
 ('Ysoekhmou', 'Yyqlgosnj', 'NE', 'Madison'),
 ('Cnagprzrnjbk', 'Mvrxvnfat', 'NY', 'Detroit'),
 ('Qwyhdbn', 'Nmfqmk', 'DC', 'Garland'),
 ('Yujcnck', 'Kjrnx', 'LA', 'Amarillo'),
 ('Vsuy', 'Qxjriuo', 'PW', 'Plano'),
 ('Fsocoysqtsus', 'Iws', 'SD', 'Madison'),
 ('Fnsx', 'Vzesg', 'ID', 'Glendale'),
 ('Caqi', 'Snuvqy', 'AR', 'Fontana'),
 ('Etrangzdmcfp', 'Ozfro', 'UT', 'Garland'),
 ('Lcwjhj', 'Bavtnfgkmmfnz', 'MT', 'Amarillo'),
 ('Qqetsa', 'Sbylaqgof', 'RI', 'Omaha'),
 ('Ywipzwqmvjae', 'Yjr', 'PA', 'El Paso'),
 ('Ojga', 'Wxtftpxu', 'KS', 'Wichita'),
 ('Wjmfqnlnl', 'Yfkaxpavpfs', 'MT', 'Anaheim'),
 ('Vfsnpniouyxf', 'Nelc', 'VI', 'Reno'),
 ('Yxvam', 'Wbicltygmpd', 'WV', 'Colorado Springs'),
 ('Wthafrmvqdvxv', 'Mmskpbsqmijl', 'LA', 'Houston'),
 ('Ykaxrcrrcepp', 'Zhpegqi', 'SC', 'Huntsville'),
 ('Tsyidn', 'Hxewhnfkevklj', 'AK', 'Portland'),
 ('Zhwqly', 'Qjea', 'WA', 'El Paso'),
 ('Kioxjifaw', 'Yssvqtkcscdj', 'GA', 'Irvine'),
 ('Zlxxzkfuztih', 'Lb', 'OH', 'Richmond'),
 ('Vub', 'Rlsrrlfvrt', 'MA', 'Tempe'),
 ('Fc', 'Tciubmjdy', 'CA', 'Los Angeles'),
 ('Nazs', 'Abihodaxwoeb', 'MA', 'Cincinnati'),
 ('Llza', 'Lzwfu', 'ID', 'Modesto'),
 ('Lldp', 'Nvyryhlayiu', 'OR', 'Amarillo'),
 ('Ajwcb', 'Zjjgiuubonmj', 'NC', 'Irving'),
 ('Rpnvkaqku', 'Xxqtym', 'DE', 'Des Moines'),
 ('Xki', 'Hkkrhivbbqsgn', 'AK', 'Kansas City'),
 ('Bvt', 'Dltvctcgv', 'ID', 'San Antonio'),
 ('Qcbnnwume', 'Iezrfje', 'WI', 'North Las Vegas'),
 ('Kgkxadnuiy', 'Oynulkme', 'NM', 'Minneapolis'),
 ('Sfizz', 'Cnigzszffbagj', 'NC', 'Chandler'),
 ('Nsexbjcwz', 'Lpgv', 'SD', 'Glendale'),
 ('Wfbbedpr', 'Pih', 'MI', 'Greensboro'),
 ('Iqujdpqoy', 'Fkfs', 'ND', 'Tallahassee'),
 ('Okuolgsapf', 'Xsbhnlazizx', 'MP', 'Wichita'),
 ('Omeohjp', 'Uwidcwhmhu', 'DC', 'Amarillo'),
 ('Oipg', 'Znczh', 'MH', 'Winston-Salem'),
 ('Jsfvdcuu', 'Stj', 'VI', 'Huntsville'),
 ('Euxodyvoyfrad', 'Wcpbne', 'CO', 'Winston-Salem'),
 ('Ietoowrh', 'Epsdnmtw', 'FL', 'Tucson'),
 ('Bnqxnhvelyzhe', 'Kwfroyprpzbx', 'DC', 'Jacksonville'),
 ('Hcb', 'Fwckfdmjpzv', 'IL', 'San Bernardino'),
 ('Fkjzmqddxwr', 'Kmvczgju', 'AZ', 'San Diego'),
 ('Kfzvtkhtsycih', 'Orbpbfqo', 'LA', 'Hialeah'),
 ('Xpweso', 'Qzcckadqlun', 'WY', 'Bakersfield'),
 ('Skhl', 'Yn', 'DC', 'Pittsburgh'),
 ('Lc', 'Tuxfzkvqwpga', 'MI', 'Tampa'),
 ('Xovuhssqywpaz', 'Tdnnrqb', 'NM', 'Philadelphia'),
 ('Bghxa', 'Ksov', 'WV', 'Los Angeles'),
 ('Rkmpcemsnhn', 'Hcsafeazcoizo', 'AL', 'Denver'),
 ('Lgmafc', 'Hdqeyl', 'NM', 'Charlotte'),
 ('Lwwioy', 'Rclae', 'NH', 'Lincoln'),
 ('Ndphaco', 'Jrww', 'IN', 'Irving'),
 ('Xzv', 'Vk', 'AK', 'Greensboro'),
 ('Xgtie', 'Yq', 'KS', 'Worcester'),
 ('Qwvemkbjlm', 'Jas', 'MD', 'Honolulu'),
 ('Iatokxosmmqy', 'Uhwlwloh', 'WA', 'Baltimore'),
 ('Jb', 'Tz', 'AR', 'Austin'),
 ('Clpfoglf', 'Lnya', 'IA', 'Reno'),
 ('Jdkukhgfdrbp', 'Gycmelipdd', 'UT', 'Moreno Valley'),
 ('Lf', 'Rsjblypkt', 'SD', 'Port St. Lucie'),
 ('Qmgir', 'Fstcou', 'SD', 'Jackson'),
 ('Labw', 'Pwhsqz', 'MI', 'Orlando'),
 ('Kmulpbvgipcpt', 'Nb', 'HI', 'Riverside'),
 ('Zpuiuptymgr', 'Rbovdqppqnobi', 'CA', 'Bakersfield'),
 ('Byjotsm', 'Nx', 'PW', 'Rancho Cucamonga'),
 ('Yjah', 'Luffmpglly', 'IA', 'Sacramento'),
 ('Fwtaapyoekd', 'Aggbweooa', 'KY', 'St. Paul'),
 ('Gq', 'Fvg', 'UT', 'Buffalo'),
 ('Ysrt', 'Qmvi', 'MN', 'Los Angeles'),
 ('Mkh', 'Fwakgxaphlcw', 'KS', 'Port St. Lucie'),
 ('Kneeid', 'Djjsitcait', 'PA', 'Cincinnati'),
 ('Tufrbermlnjpk', 'Qc', 'NV', 'Greensboro'),
 ('Yp', 'Hdv', 'NM', 'Providence'),
 ('Uccisbipns', 'Hxekvtmqkvoo', 'PW', 'Mobile'),
 ('Fqteepfdr', 'Rgrd', 'AZ', 'Chattanooga'),
 ('Coeyhfmrw', 'Iwzrkeslx', 'MN', 'Jackson'),
 ('Qflcq', 'Jfzpb', 'SD', 'North Las Vegas'),
 ('Ysfbufoj', 'Mfoyhdhvzgru', 'KY', 'Lubbock'),
 ('Ernnfo', 'Ojurtefjadq', 'NC', 'Madison'),
 ('Yktdqnuodayjg', 'Keupfogpq', 'PR', 'St. Petersburg'),
 ('Icdkdvg', 'Zzcxwtavslcwa', 'FL', 'Louisville/Jefferson County'),
 ('Tkkgcq', 'Miawhb', 'CT', 'Wichita'),
 ('Viyvnkfcdn', 'Xakbwojll', 'WV', 'Augusta-Richmond County'),
 ('Ihhoyw', 'Ibivpa', 'KS', 'Brownsville'),
 ('Qpxqigbz', 'Rrnhjzowkuu', 'ME', 'Anchorage'),
 ('Oau', 'Jhdxr', 'KS', 'Providence'),
 ('Ucmscazcbon', 'Sqsiomlrcetvz', 'ID', 'Lexington-Fayette'),
 ('Ghpjosfptouo', 'Uwgcih', 'NJ', 'St. Paul'),
 ('Nhybthmyedaz', 'Vxuajgadiityq', 'OH', 'Philadelphia'),
 ('Aeypah', 'Aifalfojdman', 'RI', 'Mobile'),
 ('Vlxactvjmd', 'Vjyqrngydbhix', 'MS', 'Charlotte'),
 ('Xqsybbap', 'Qthogyayegfx', 'KS', 'Baton Rouge'),
 ('Gtemibugllah', 'Blnamzhupqd', 'VA', 'Newport News'),
 ('Btqxaelxzwlcz', 'Lxcflysmzecg', 'MS', 'Stockton'),
 ('Astfvzgotg', 'Kd', 'WI', 'Providence'),
 ('Ocm', 'Vkforid', 'ND', 'Scottsdale'),
 ('Fw', 'Umihitqwbvl', 'MT', 'Lexington-Fayette'),
 ('Rksyiahznud', 'Yojqa', 'MN', 'Lexington-Fayette'),
 ('Dgphwkxqzps', 'Kqaqhzpqejfmi', 'VT', 'Fresno'),
 ('Btgbzs', 'Wqzhzra', 'ND', 'Oceanside'),
 ('Dogbwiqfne', 'Bjtytogzya', 'ID', 'Arlington'),
 ('Nndqsgieszf', 'Ftquvyliv', 'AK', 'Huntington Beach'),
 ('Fiechhkt', 'Ut', 'MT', 'Irving'),
 ('Rq', 'Romxrwmmwy', 'ND', 'Indianapolis'),
 ('Tisejewwcii', 'Bwzosfbpiplt', 'FM', 'Anaheim'),
 ('Jqlbsvjlajj', 'Szlvrjzdsuj', 'MD', 'Dallas'),
 ('Gshatuxscjw', 'Smxtwpyoohgn', 'MT', 'Aurora'),
 ('Lxfn', 'Nud', 'KS', 'Little Rock'),
 ('Kbkdma', 'Juxu', 'AZ', 'Albuquerque'),
 ('Hlpde', 'Oejumayrbtf', 'NE', 'Gilbert'),
 ('Qyxaw', 'Mpxqvq', 'NY', 'Jacksonville'),
 ('Pgdrxjycqx', 'Ubthcv', 'SC', 'Austin'),
 ('Zhior', 'Limhf', 'NJ', 'Dallas'),
 ('Zzubjbkbtlmj', 'Kho', 'MS', 'Philadelphia'),
 ('Weri', 'Dscbnscuhom', 'MI', 'Garland'),
 ('Yeyzqyna', 'Ygmo', 'ND', 'Rancho Cucamonga'),
 ('Shtyorbv', 'Uq', 'MT', 'Boise City'),
 ('Fnxxrc', 'Yqyavvkbrnw', 'CO', 'Fort Lauderdale'),
 ('Qzjmrazyv', 'Sdtn', 'AR', 'Newark'),
 ('Eme', 'Ubpsqwgqqr', 'NC', 'Omaha'),
 ('Aiopeug', 'Wxu', 'AZ', 'Tempe'),
 ('Bs', 'Poo', 'MN', 'Scottsdale'),
 ('Lstrosvzifvb', 'Rwafolhvx', 'FM', 'Madison'),
 ('Mfbqeseike', 'Vwih', 'OR', 'Chula Vista'),
 ('Lx', 'Nasonlbiwa', 'NE', 'Fort Wayne'),
 ('Kxaufunc', 'Nwqrezrwdqdc', 'AK', 'Augusta-Richmond County'),
 ('Ypu', 'Oqdbolyjtyadr', 'MI', 'Cincinnati'),
 ('Gjvcfpzdfyq', 'Wlolqyfslxi', 'NY', 'Anchorage'),
 ('Evxkr', 'Oclnuwwoldn', 'MO', 'Lubbock'),
 ('Jfcfyhmrqdxpo', 'Reetgwa', 'AS', 'Seattle'),
 ('Mqawhzjprzjf', 'Xnd', 'AR', 'Reno'),
 ('Oirjpqsp', 'Xgpqcgxv', 'VI', 'Grand Rapids'),
 ('Xxxgwoqpuj', 'Wohzernd', 'WA', 'Phoenix'),
 ('Zhwnhyyl', 'Lhxlcjzyvxli', 'TN', 'Little Rock'),
 ('Ebxmvovsti', 'Uviaukhfmms', 'OH', 'Mobile'),
 ('Wabmrjxswn', 'Tcazqjar', 'MT', 'Nashville-Davidson'),
 ('Jbmggrd', 'Aibyaf', 'OH', 'Chandler'),
 ('Ozvrd', 'Niffmcuopml', 'VT', 'Milwaukee'),
 ('Gqlawl', 'Mm', 'SD', 'Orlando'),
 ('Rdxgvxey', 'Qy', 'OK', 'Baltimore'),
 ('Tfodherpvsh', 'Qunghjkhra', 'MD', 'Oxnard'),
 ('Jvwp', 'Xcpqqywd', 'CT', 'Greensboro'),
 ('Bojkwvoheb', 'Brhwcohxtxkd', 'MO', 'Pittsburgh'),
 ('Qqgbvcffumk', 'Qigwqmbcltmej', 'MH', 'Overland Park'),
 ('Kdzk', 'Kkb', 'VA', 'Denver'),
 ('Hpgepkwzyr', 'Aqbkljt', 'ND', 'Fort Lauderdale'),
 ('Hrmhajsp', 'Fp', 'VI', 'Columbus'),
 ('Fbywrrqv', 'Yaulubqpyyx', 'WY', 'Modesto'),
 ('Aqqvpltwgxey', 'Prmvteod', 'MI', 'Rochester'),
 ('Vywfmotf', 'Wtap', 'CT', 'Des Moines'),
 ('Kskkhqc', 'Fquvfypxh', 'SC', 'Spokane'),
 ('Hjatoctvwcwu', 'Dmgj', 'OH', 'Port St. Lucie'),
 ('Ypiqyiee', 'Wotkfvpdxy', 'MS', 'Garland'),
 ('Acurxphxulzs', 'Oog', 'SC', 'Lincoln'),
 ('Fvfuxv', 'Rn', 'WY', 'Washington'),
 ('Yvuy', 'Wrpuc', 'MP', 'Scottsdale'),
 ('Ubenzrznys', 'Retbk', 'NC', 'Mesa'),
 ('Dctxe', 'Kemj', 'VI', 'Glendale'),
 ('Mntglu', 'Srlgt', 'TN', 'Denver'),
 ('Xra', 'Lxbsr', 'OK', 'Toledo'),
 ('Bxwswbgsrmfl', 'Ssa', 'MO', 'Fontana'),
 ('Czfwarxclp', 'Rytdo', 'CO', 'Tampa'),
 ('Nwdvxk', 'Fyhwchkwndbt', 'MD', 'Raleigh'),
 ('Fsmholtw', 'Ijsvdk', 'AK', 'Orlando'),
 ('Cdimqk', 'Cccwqlqq', 'WV', 'Garland'),
 ('Ntkvsdvu', 'Pcctsjwidjr', 'IA', 'Jackson'),
 ('Ueuolsk', 'Fonzhjtoqqn', 'TN', 'Vancouver'),
 ('Lndttjm', 'Kwncfeh', 'MA', 'Yonkers'),
 ('Tecjkx', 'Blctcwpe', 'VA', 'Atlanta'),
 ('Lasqvepxj', 'Ixphnjwtgxip', 'AL', 'Chattanooga'),
 ('Jxscngbawn', 'Fgbdbzeojt', 'NJ', 'Long Beach'),
 ('Czx', 'Mwltdmc', 'SC', 'Chula Vista'),
 ('Uqrk', 'Fkg', 'NC', 'Fort Lauderdale'),
 ('Pha', 'Utbwkruul', 'SD', 'Vancouver'),
 ('Srtbb', 'Bvapdyjh', 'MT', 'Albuquerque'),
 ('Jlcy', 'Uhtlxh', 'TX', 'Santa Rosa'),
 ('Szwuk', 'Rlwviacvcyj', 'MS', 'Akron'),
 ('Qh', 'Moimj', 'GA', 'Oklahoma City'),
 ('Dsfb', 'Xousyga', 'KY', 'Tempe'),
 ('Cllqozv', 'Echrct', 'VT', 'Milwaukee'),
 ('Rbpq', 'Obw', 'AZ', 'Oakland'),
 ('Noimrnx', 'Dtpcpyanpt', 'TN', 'Buffalo'),
 ('Ikejsifjtps', 'Fibknuxvwmdui', 'GU', 'Garland'),
 ('Zpxegdegvdo', 'Mthf', 'AL', 'Brownsville'),
 ('Rpfvgzmz', 'Frtomadgxsz', 'WY', 'Wichita'),
 ('Tpe', 'Xbtfsdjhmjbl', 'NM', 'Fremont'),
 ('Zmxufrgjfwu', 'Ubaryaajty', 'MI', 'El Paso'),
 ('Wjugjkgp', 'Amwsnkf', 'CT', 'Anchorage'),
 ('Vwskvjmpdtgki', 'Plkyfnxkxqkmi', 'WY', 'Fremont'),
 ('Acv', 'Fvv', 'TN', 'Houston'),
 ('Wmqdmxshyzv', 'Pmj', 'IA', 'Winston-Salem'),
 ('Iyrebgxkmn', 'Ocmbuokvjrm', 'OR', 'Rancho Cucamonga'),
 ('Snxhgwbojyilj', 'Jigegw', 'OK', 'Tempe'),
 ('Nqdtrjxigkw', 'Dclmh', 'IL', 'Des Moines'),
 ('Qbble', 'Jxct', 'KS', 'Durham'),
 ('Rwqyxczrfqm', 'Haggxojwxcup', 'SC', 'Yonkers'),
 ('Htelnpwvb', 'Jqk', 'AL', 'Akron'),
 ('Ncujxwrynsywf', 'Yjrughyvinjtt', 'SC', 'Columbus'),
 ('Nwqqkxhdygaye', 'Tvqnyu', 'MT', 'Boston'),
 ('Mrvpuebg', 'Byc', 'MT', 'Louisville/Jefferson County'),
 ('Ubmf', 'Tusxnaggee', 'MS', 'Huntington Beach'),
 ('Udawcgtn', 'Sudytasjdd', 'HI', 'Pittsburgh'),
 ('Zeccrfsn', 'Hfs', 'ID', 'Aurora'),
 ('Zrixtdq', 'Kivqr', 'NH', 'Montgomery'),
 ('Vpohn', 'Weyxmqye', 'CO', 'Providence'),
 ('Njx', 'Jwytedd', 'ID', 'Chandler'),
 ('Noa', 'Vcafqgeolhw', 'NH', 'Oceanside'),
 ('Dqaqegpcwg', 'Bodsrtdhhk', 'WA', 'Madison'),
 ('Mtbvm', 'Kgav', 'KS', 'Columbus'),
 ('Klcpkxyiv', 'Wtrlq', 'MI', 'Oceanside'),
 ('Erunc', 'Rbiwygxdwk', 'LA', 'Chicago'),
 ('Gouswfgoewb', 'Pmwvgvs', 'MI', 'Tulsa'),
 ('Xgc', 'Ehmyplzrgrzd', 'NJ', 'Austin'),
 ('Lezuxmcd', 'Fmbaoiajp', 'LA', 'Honolulu'),
 ('Pzrxtsjrnz', 'Jxvkonzyv', 'NM', 'Portland'),
 ('Zzpiru', 'Jkqyrmtbqsm', 'VI', 'Cincinnati'),
 ('Obvbcjfv', 'Pccs', 'WI', 'Worcester'),
 ('Xxwazu', 'Adtxlsqi', 'NE', 'Rancho Cucamonga'),
 ('Rfc', 'Szlfqmdhakaq', 'WV', 'Mesa'),
 ('Cxenb', 'Wbkskfos', 'PR', 'San Jose'),
 ('Fubpvvb', 'Vttltafg', 'AS', 'Baton Rouge'),
 ('Tjoczkebd', 'Ghkg', 'NJ', 'Spokane'),
 ('Fnplrrdfsh', 'Ex', 'RI', 'Memphis'),
 ('Uxuujklk', 'Zmnvqkqwzr', 'SC', 'Glendale'),
 ('Znozqsczm', 'Am', 'WV', 'Lincoln'),
 ('Fyybxkikxyuac', 'Dykzokzd', 'VA', 'Memphis'),
 ('Zvq', 'Mifhjaterodzo', 'GU', 'Brownsville'),
 ('Idkiugfcub', 'Atijs', 'DE', 'Houston'),
 ('Ifuafeox', 'Sfk', 'MH', 'St. Petersburg'),
 ('Mim', 'Ei', 'MN', 'Arlington'),
 ('Npdlz', 'Yaandqjgzmbgm', 'KS', 'Oxnard'),
 ('Aebkyb', 'Hbshtlwwx', 'ID', 'Henderson'),
 ('Ugg', 'Nqqvv', 'UT', 'Philadelphia'),
 ('Xwqnazvli', 'Dvuiaobepgq', 'AZ', 'Gilbert'),
 ('Mdhyb', 'Kwjtdppd', 'WV', 'Irvine'),
 ('Osjxtduzfcpyo', 'Jinzbk', 'WV', 'Houston'),
 ('Yzuow', 'Neexeeqkkw', 'MS', 'San Diego'),
 ('Ln', 'Grvgfeghdhgsj', 'FM', 'Providence'),
 ('Gjfsdcn', 'Ezkmjryr', 'NV', 'Tucson'),
 ('Cbbowtedrvmn', 'Czgcjyd', 'OK', 'Shreveport'),
 ('Fz', 'Ksaexshp', 'NC', 'Corpus Christi'),
 ('Cqwuho', 'Xeiqp', 'FL', 'Fort Worth'),
 ('Chmjtwbvfny', 'Kgaswti', 'ID', 'Nashville-Davidson'),
 ('Wf', 'Pdwkc', 'MT', 'Portland'),
 ('Lrlvuogbgdgs', 'Tskrkfu', 'KY', 'Corpus Christi'),
 ('Abiuhsuvh', 'Fzullcgxqhkyy', 'MN', 'North Las Vegas'),
 ('Lgatgfouy', 'Hplpgaketfoin', 'PA', 'Little Rock'),
 ('Gnlmnjzfkxks', 'Seudsccumx', 'GA', 'Chicago'),
 ('Rq', 'Gkegkzacxvxuh', 'DC', 'Los Angeles'),
 ('Rzdqpex', 'Gltjaynoosdw', 'GU', 'Wichita'),
 ('Ixpd', 'Jadedpwtlt', 'LA', 'Lubbock'),
 ('Gubeojdqlylne', 'Jxhz', 'MT', 'San Diego'),
 ('Cssb', 'Srnvykvfqvxrh', 'NJ', 'Oxnard'),
 ('Mounijch', 'Tpsmhwdsmttbk', 'MA', 'Santa Ana'),
 ('Gszwxryoizeu', 'Asyow', 'TX', 'Chula Vista'),
 ('Dtajsmsjiozbg', 'Ipbngkbortfu', 'KY', 'Seattle'),
 ('Drdmxbrfpj', 'Dtnda', 'MI', 'Bakersfield'),
 ('Twyi', 'Eqbcijcgtijsr', 'KY', 'Atlanta'),
 ('Ifqbwzlzcivam', 'Fjra', 'DE', 'Fresno'),
 ('Rcrkpvatoueox', 'Bai', 'GU', 'Scottsdale'),
 ('Jmbdihypu', 'Xzjyyst', 'NC', 'Lincoln'),
 ('Wofkxzxgo', 'Ejvrfsvlm', 'SD', 'Irvine'),
 ('Gikxcylbykj', 'Ucoyytvnai', 'ME', 'Akron'),
 ('Vftonsf', 'Cxrurqysarwmz', 'DC', 'New York'),
 ('Nbyivfbcpcw', 'Lozkxchuhgma', 'IA', 'Fayetteville'),
 ('Gfzhndikg', 'Ygec', 'CT', 'Oceanside'),
 ('Bzlsrydrbhhd', 'Brvckto', 'MH', 'Amarillo'),
 ('Nqiexiu', 'Zqizp', 'VT', 'San Jose'),
 ('Ouaiv', 'Whqw', 'WI', 'Santa Rosa'),
 ('Hgwawkq', 'Tpjyrtclzab', 'IL', 'Grand Prairie'),
 ('Qwklmimnelw', 'Kao', 'WI', 'Pittsburgh'),
 ('Czxfqbqixcxs', 'Ulslpmtaer', 'UT', 'Gilbert'),
 ('Il', 'Tseuwipohixxp', 'CT', 'Amarillo'),
 ('Qrjiyc', 'Ih', 'MD', 'Grand Rapids'),
 ('Nwahqjd', 'Mukdakgyaw', 'ME', 'Toledo'),
 ('Woojhdto', 'Sbpah', 'CO', 'Providence'),
 ('Of', 'Ugjmq', 'WA', 'Mobile'),
 ('Hgcbuvuniwiap', 'Kqqjhabcb', 'CT', 'Fort Lauderdale'),
 ('Pxudtxf', 'Gmhhv', 'AZ', 'Oklahoma City'),
 ('Mtcsuxaxkw', 'Rzk', 'KS', 'Louisville/Jefferson County'),
 ('Eplsnko', 'Dqcyp', 'MS', 'El Paso'),
 ('Hhfuvnmuus', 'Qy', 'LA', 'Charlotte'),
 ('Bsuxzit', 'Kmhs', 'SC', 'Oakland'),
 ('Xdggfxke', 'Smviuruzffxy', 'SC', 'Seattle'),
 ('Pfgwqf', 'Fcb', 'GU', 'Stockton'),
 ('Gtc', 'Veolsmtenoz', 'MN', 'Birmingham'),
 ('Zmwmcgntmaa', 'Gk', 'TX', 'Aurora'),
 ('Bf', 'Aay', 'MT', 'Pittsburgh'),
 ('Tkozxyncyfrfl', 'Zydndkap', 'NH', 'Dallas'),
 ('Mqhthjvmm', 'Ewwp', 'KS', 'Newark'),
 ('Daoffs', 'Bg', 'WI', 'San Jose'),
 ('Zbohjittadw', 'Plghl', 'IA', 'Garland'),
 ('Sfcelfzpqo', 'Dw', 'AR', 'Reno'),
 ('Aeco', 'Sg', 'HI', 'Santa Rosa'),
 ('Iridbq', 'Apsfwquas', 'TX', 'St. Louis'),
 ('Jztbdhtwpba', 'Fr', 'IN', 'Winston-Salem'),
 ('Mvjdtfly', 'Dkigptgpul', 'PA', 'El Paso'),
 ('Syjx', 'En', 'GA', 'Cincinnati'),
 ('Uovzmnh', 'Lbivwidbmpdk', 'AS', 'Louisville/Jefferson County'),
 ('Myneipsslktvm', 'Bzwhtjhlgw', 'WV', 'Cape Coral'),
 ('Lfqaoeouhpzz', 'Jdappeqq', 'DE', 'Lubbock'),
 ('Dd', 'Atjtw', 'IL', 'Oxnard'),
 ('Nkwbrkrxof', 'Mbbwiopcaurvx', 'MN', 'Kansas City'),
 ('Uwbj', 'Mvtcpnelwoiu', 'MN', 'Buffalo'),
 ('Wbt', 'Zzkr', 'IL', 'Portland'),
 ('Ytxocztwg', 'Ealfervois', 'OR', 'Rochester'),
 ('Vfvnx', 'Wrderrmoorvup', 'NV', 'Dallas'),
 ('Dxsnjan', 'Iizhtare', 'AL', 'Atlanta'),
 ('Aner', 'Vcwfj', 'ID', 'Oceanside'),
 ('Patvfohlml', 'Kwtd', 'PW', 'Cleveland'),
 ('Rphddj', 'Brzow', 'RI', 'Baltimore'),
 ('Muxclpbs', 'Pt', 'MI', 'Huntington Beach'),
 ('Cvzzjgwqhsm', 'Gcrufbkq', 'MO', 'Henderson'),
 ('Ljsjr', 'Rtielmdrnes', 'RI', 'Columbus'),
 ('Tfnumwsbwcea', 'Akxewmwrfelv', 'KS', 'Augusta-Richmond County'),
 ('Tqzoxs', 'Ucdn', 'WY', 'Port St. Lucie'),
 ('Xd', 'Wkinndizjc', 'OR', 'Santa Clarita'),
 ('Jkmwqfqxkaut', 'Opb', 'SD', 'Akron'),
 ('Juvrxlvl', 'Zqrlmjernrgjl', 'CO', 'Houston'),
 ('Vsljlwgew', 'Vyqqoavb', 'HI', 'St. Paul'),
 ('Ojrtxco', 'Mox', 'ID', 'San Diego'),
 ('Emkzy', 'Qszht', 'AL', 'Garland'),
 ('Acnczki', 'Relwdhnaiur', 'WV', 'Rochester'),
 ('Hgawsjq', 'Feqcidqydgprl', 'MP', 'Salt Lake City'),
 ('Lmqxf', 'Zjhnmhs', 'NY', 'Irving'),
 ('Pjndlaertqs', 'Vthrstecd', 'OH', 'Stockton'),
 ('Icyku', 'Fjb', 'VT', 'Chula Vista'),
 ('Qjmyucpat', 'Fyb', 'CO', 'Plano'),
 ('Rowho', 'Lmmkafu', 'DC', 'Tacoma'),
 ('Mxskfhevqvy', 'Hynqqjxlhdh', 'PW', 'Louisville/Jefferson County'),
 ('Jsanrcyvb', 'Dafxobjtocxqx', 'FL', 'Irving'),
 ('Qarbzqtifc', 'Enmtyfmlbfuu', 'LA', 'Vancouver'),
 ('Wzvoebjkexgo', 'Eqyrehggvsug', 'LA', 'Dallas'),
 ('Ckorcbtbvlril', 'Fj', 'FM', 'Fayetteville'),
 ('Xplsanwrmrjw', 'Ua', 'AR', 'Mobile'),
 ('Ixfbcjk', 'Ofn', 'VA', 'Plano'),
 ('Mljnobvjcejg', 'Jdnjxmrq', 'UT', 'Chattanooga'),
 ('Sbwoyrefcrv', 'Wuqzak', 'FL', 'Newark'),
 ('Dmrmecolqezc', 'Ccykmjduhsktz', 'UT', 'Birmingham'),
 ('Eutxiaccodgt', 'Nhr', 'IN', 'Milwaukee'),
 ('Xkg', 'Ydgxrh', 'TN', 'Lincoln'),
 ('Nbkbewikmmx', 'Vcvwxoneawg', 'PA', 'Jersey City'),
 ('Nzhguhq', 'Cqq', 'UT', 'Santa Clarita'),
 ('Jksgkioux', 'Klnfbhodbmqw', 'GA', 'Dallas'),
 ('Qw', 'Ra', 'VA', 'Grand Prairie'),
 ('Lnwwi', 'Riqd', 'NJ', 'Miami'),
 ('Yqrehhubzh', 'Waqtsrlxc', 'SC', 'Louisville/Jefferson County'),
 ('Fahvnfoop', 'Ebkgprcyyim', 'MT', 'Vancouver'),
 ('Bc', 'Rwlp', 'KY', 'Long Beach'),
 ('Dqw', 'Cszmfzvg', 'MP', 'Huntington Beach'),
 ('Askbhb', 'Srzxvlxgt', 'PR', 'Rancho Cucamonga'),
 ('Cznmyrrxffbp', 'Rxs', 'FM', 'Cape Coral'),
 ('Oar', 'Wj', 'GA', 'Boise City'),
 ('Lpsj', 'Sbqmrorho', 'DE', 'Raleigh'),
 ('Tifygfzo', 'Xmultbhxjs', 'MO', 'Nashville-Davidson'),
 ('Dmtgnrtexfd', 'Dulyjw', 'WA', 'Grand Prairie'),
 ('Nggawwybeiy', 'Plmvpt', 'AS', 'Cleveland'),
 ('Veusvewucld', 'Vnjjgecti', 'CO', 'Providence'),
 ('Oiwvzrbpzonrw', 'Mwt', 'TX', 'Anaheim'),
 ('Clcgkri', 'Qczfptlqf', 'MA', 'Nashville-Davidson'),
 ('Pcjfoevaho', 'Aevp', 'VA', 'Orlando'),
 ('Su', 'Stjltj', 'FM', 'Omaha'),
 ('Af', 'Ayyxafrmlbv', 'SD', 'San Antonio'),
 ('Uv', 'Ybfnlir', 'MN', 'Ontario'),
 ('Qkwlerl', 'Qfomyoa', 'MH', 'Laredo'),
 ('Vewyyzsnt', 'Jxhddhpabiv', 'MT', 'Santa Clarita'),
 ('Bfbsnaarsxy', 'Cbd', 'AS', 'Fontana'),
 ('Qf', 'Xzapjcypzmsxe', 'NY', 'Norfolk'),
 ('Ziqglojosee', 'Nafndxi', 'OK', 'Rochester'),
 ('Hsoyqopk', 'Xdp', 'AS', 'Austin'),
 ('Izndos', 'Oousckzh', 'MN', 'Port St. Lucie'),
 ('Xsh', 'Pfuqdjfyslexj', 'MS', 'Oklahoma City'),
 ('Qarjf', 'Qukykmyvr', 'OH', 'Anchorage'),
 ('Cdnepyejjbneq', 'Rquyhywkw', 'TN', 'Reno'),
 ('Uvlwyh', 'Dikf', 'OH', 'Garden Grove'),
 ('Doqwkpbdbeowc', 'Clhbb', 'IL', 'Oxnard'),
 ('Ogmvgccqkp', 'Mqkjnhiabrf', 'GA', 'Pittsburgh'),
 ('Nqssugxqx', 'Mvr', 'PR', 'Greensboro'),
 ('Beohobs', 'Mep', 'RI', 'Irvine'),
 ('Wkv', 'Vxas', 'WY', 'Bakersfield'),
 ('Pjauahoqjxyck', 'Yukfftqtv', 'HI', 'Norfolk'),
 ('Hihjmfcjchoyv', 'Ptwieesl', 'ID', 'Louisville/Jefferson County'),
 ('Wleihdykxtixy', 'Aazaf', 'PA', 'Colorado Springs'),
 ('Rjtcnp', 'Ghmdgga', 'ME', 'Baltimore'),
 ('Srrftyomdyafk', 'Wqtstajjw', 'NJ', 'Huntsville'),
 ('Hglmwkysbgynz', 'Gsj', 'AR', 'Fontana'),
 ('Jeclxw', 'Hepwjlofjj', 'GA', 'Columbus'),
 ('Daf', 'Scopgxgt', 'CT', 'Orlando'),
 ('Dtdolw', 'Sbbpoxgzhod', 'ME', 'Fayetteville'),
 ('Oeekloxlqk', 'Mlgyfpl', 'NY', 'Salt Lake City'),
 ('Fgkgpepvyja', 'Dgtsmrohac', 'MS', 'Boston'),
 ('Fhrsfbriv', 'Douvvyshdn', 'AS', 'Garland'),
 ('Mwxwhqftlxth', 'Feudpdsjv', 'MI', 'Fontana'),
 ('Ongnazayo', 'Swknxvrfoepur', 'SC', 'Dallas'),
 ('Vagn', 'Ssqbmoagh', 'NJ', 'San Bernardino'),
 ('Daelnljw', 'Feipgdlx', 'NM', 'Grand Rapids'),
 ('Fttzwkmwzgb', 'Revcvt', 'NH', 'Denver'),
 ('Lcaqqp', 'Osf', 'VA', 'Washington'),
 ('Jlmnhkotbvndc', 'Ht', 'KS', 'Oceanside'),
 ('Id', 'Mxrtbtcdnoqob', 'GU', 'Tulsa'),
 ('Lgolzs', 'Uhqwkn', 'NE', 'Rochester'),
 ('Ob', 'Wtikcl', 'IA', 'Fontana'),
 ('Zyazuc', 'Xquoawj', 'IA', 'Tampa'),
 ('Wwfwmjyr', 'Oeze', 'PR', 'San Antonio'),
 ('Qigcrrnv', 'Vyoogbq', 'MN', 'Plano'),
 ('Pghmbvphxqxlz', 'Lct', 'AR', 'Chula Vista'),
 ('Wnemybtm', 'Mumkyezaeeek', 'VA', 'Yonkers'),
 ('Ndhu', 'Srqluhkkyppzu', 'VT', 'Newark'),
 ('Ognmrs', 'Qsa', 'TX', 'Chula Vista'),
 ('Vloooqcrhi', 'Fxh', 'MN', 'Ontario'),
 ('Wtfafg', 'Stsycswq', 'MP', 'Grand Prairie'),
 ('Iralbynecfyg', 'Aiu', 'AS', 'Glendale'),
 ('Wzleoaws', 'Rcd', 'VI', 'Modesto'),
 ('Kuywlhdq', 'Nizmvx', 'VA', 'Oklahoma City'),
 ('Kxnvigbvnij', 'Paievx', 'DE', 'Philadelphia'),
 ('Vaagbvxhx', 'Eqltnif', 'MI', 'Grand Prairie'),
 ('Hfboxgrnclmw', 'Ybtging', 'OK', 'Huntsville'),
 ('Jvuzljiyp', 'Qk', 'SC', 'Plano'),
 ('Aehnjiks', 'Nbxlnaf', 'PR', 'Colorado Springs'),
 ('Xgfjisfld', 'Kcxphqsvlm', 'NE', 'Tulsa'),
 ('Gcqtpai', 'Qnyfsa', 'IA', 'Honolulu'),
 ('Kk', 'Rqwmpkepjx', 'KY', 'St. Paul'),
 ('Pc', 'Bgwarfw', 'RI', 'Scottsdale'),
 ('Wtny', 'Uvjpvq', 'PW', 'Austin'),
 ('Ktxlpehauf', 'Apfaxlnzxfyvr', 'CA', 'Santa Rosa'),
 ('Laesnfez', 'Mmfz', 'NC', 'Houston'),
 ('Jeqcslsai', 'Zynnawjzjyu', 'PR', 'Rochester'),
 ('Gkpnysh', 'Inpezfdxorj', 'MS', 'Louisville/Jefferson County'),
 ('Ccoxkahefj', 'Varfbz', 'AL', 'Vancouver'),
 ('Flnyrl', 'Dcbyvpvzs', 'WI', 'Washington'),
 ('Nrwv', 'Zwrllbzausv', 'SD', 'Detroit'),
 ('Jfwboeohaifoc', 'Xtcquqdzzkdi', 'NY', 'Santa Rosa'),
 ('Xmnvkpgzzaad', 'Hoeswqqwbeejx', 'PR', 'Baltimore'),
 ('Ed', 'Nomgfbhktiw', 'ME', 'Boston'),
 ('Xdxpxpku', 'Wwiz', 'TN', 'Jersey City'),
 ('Rgzoptb', 'Gwjxcrbiwe', 'VI', 'El Paso'),
 ('Ca', 'Gnjzgecp', 'GU', 'Birmingham'),
 ('Lalpjoibqspmo', 'Wldzwkqzzqgoc', 'NV', 'Baltimore'),
 ('Eevh', 'Zwgwrnzfwqqr', 'HI', 'San Jose'),
 ('Lvxnhbatqyp', 'Zobahsbgdpxa', 'ND', 'Portland'),
 ('Xeh', 'Allk', 'NH', 'Birmingham'),
 ('Mhuisldbdxss', 'Ijimbwkghqnf', 'AR', 'Dallas'),
 ('Zwgksqh', 'Gjktzlza', 'UT', 'Yonkers'),
 ('Cgj', 'Lha', 'MA', 'Virginia Beach'),
 ('Cnxb', 'Aqozgn', 'MP', 'Baltimore'),
 ('Gblbntks', 'Dw', 'MO', 'Lubbock'),
 ('Uybyuq', 'Hxeqfsn', 'AR', 'Rancho Cucamonga'),
 ('Vqkkywypblblk', 'Ybkeqjsqsk', 'IN', 'Wichita'),
 ('Ru', 'Mzilvff', 'ME', 'Scottsdale'),
 ('Unyphydaca', 'Brs', 'FL', 'Tampa'),
 ('Dxubrhqfniijf', 'Pjlagzzyaeg', 'MN', 'Glendale'),
 ('Ngegikdlfmvcy', 'Jxgxoqqmsgpx', 'NJ', 'Jacksonville'),
 ('Orjy', 'Qieootnsgyoh', 'MS', 'Newark'),
 ('Culrsxmpt', 'Oumoqnacaj', 'WA', 'Des Moines'),
 ('Jt', 'Irhahk', 'CT', 'Charlotte'),
 ('Ihaiac', 'Thbimex', 'TX', 'Miami'),
 ('Gyimmat', 'Qocnynjjieq', 'NM', 'Tacoma'),
 ('Bndgvoplpmvrx', 'Rhgofmtyx', 'UT', 'New Orleans'),
 ('Ucz', 'Qlte', 'MP', 'Oklahoma City'),
 ('Cfbnskzwpjqts', 'Patv', 'WA', 'Grand Prairie'),
 ('Mhlwlfepmhzat', 'Dpmclfgtm', 'MN', 'St. Paul'),
 ('Pqsiqwxrz', 'Hoggf', 'HI', 'Omaha'),
 ('Yzdtxexecfxqo', 'Mjzmu', 'UT', 'Garden Grove'),
 ('Lkfmkbfbf', 'Juyiscseceq', 'AL', 'Milwaukee'),
 ('Viut', 'Ofiozcq', 'WY', 'Huntsville'),
 ('Vvte', 'Maszmxif', 'CT', 'Rancho Cucamonga'),
 ('Hvoea', 'Fiircjwyz', 'MD', 'Fort Worth'),
 ('Hspgmzzabhm', 'Cuzdbcidtdsmg', 'DE', 'Laredo'),
 ('Orfmxljvcz', 'Uvy', 'MT', 'Vancouver'),
 ('Rkhilupapnu', 'Cgkezdlcd', 'PA', 'Vancouver'),
 ('Czdg', 'Dreomyzvt', 'SD', 'Wichita'),
 ('Xjcmwrkrqzfo', 'Qrlqnteumxbi', 'LA', 'Anaheim'),
 ('Rja', 'Gkfxagzdaoaq', 'DE', 'Honolulu'),
 ('Mvnugvyea', 'Imwy', 'NC', 'Hialeah'),
 ('Mpvhtb', 'If', 'GU', 'Tempe'),
 ('Vae', 'Fh', 'MP', 'Pittsburgh'),
 ('Wjtjprmq', 'Jrjaczbixlfw', 'MT', 'New Orleans'),
 ('Faerzrb', 'Cvo', 'AL', 'Glendale'),
 ('Dmhctcrqfpkgf', 'Tnuflofbc', 'CO', 'St. Paul'),
 ('Eqwdd', 'Yyhlqzar', 'WV', 'Anchorage'),
 ('Mynajgoezz', 'Zyuqljixpx', 'TN', 'Boston'),
 ('Hvzyacou', 'Sbnmgktpwoa', 'CA', 'Bakersfield'),
 ('Qtx', 'Lkobaixgasygn', 'FL', 'Colorado Springs'),
 ('Inyv', 'Eoiapjdvskcpn', 'NE', 'Glendale'),
 ('Ijoq', 'Wlzgsgaybyef', 'WY', 'Tacoma'),
 ('Ff', 'Obm', 'KS', 'Vancouver'),
 ('Jn', 'Xswrpzxepf', 'AR', 'Henderson'),
 ('Da', 'Rzgvzfsm', 'GU', 'Indianapolis'),
 ('Nmpck', 'Rfotxjidmydxa', 'MH', 'Irvine'),
 ('Dxcheoijwdd', 'Ypz', 'FM', 'Santa Rosa'),
 ('Wyrjk', 'Qfnx', 'FL', 'Memphis'),
 ('Ylp', 'Lvsvwo', 'VI', 'Portland'),
 ('Ebbshrolyi', 'Rfofux', 'VT', 'Spokane'),
 ('Ghkamtwciufl', 'Lclihb', 'MO', 'Salt Lake City'),
 ('Tls', 'Fe', 'MA', 'Fayetteville'),
 ('Gppecwzcwrk', 'Bybbkcmwhnfs', 'VI', 'Denver'),
 ('Lar', 'Mulnddg', 'MN', 'Santa Ana'),
 ('Xomjhgyaalq', 'Rwpopvk', 'NM', 'Philadelphia'),
 ('Esklfl', 'Bdgherp', 'NJ', 'Santa Clarita'),
 ('Jmhlmnidje', 'Liffbyimsa', 'NM', 'Dallas'),
 ('Ugyhc', 'Gtjza', 'GU', 'New Orleans'),
 ('Smhgzyq', 'Fpilorry', 'AR', 'Dallas'),
 ('Zowbrta', 'Fvhyfswnabi', 'DE', 'Tampa'),
 ('Opcwl', 'Zpoyqlx', 'MH', 'Fremont'),
 ('Czqpcq', 'Wabby', 'KY', 'St. Louis'),
 ('Pjmlwscufimwo', 'Cqechhxuxlbty', 'MO', 'St. Louis'),
 ('Tvy', 'Nnvmxizptdnc', 'ID', 'Omaha'),
 ('Tejyesuqdgj', 'Ptjyrarrntt', 'TN', 'Albuquerque'),
 ('Whmtuinlp', 'Sdfhw', 'AR', 'Chula Vista'),
 ('Ffgddgecg', 'Ks', 'PA', 'Chattanooga'),
 ('Mv', 'Nbdgzfgl', 'PA', 'Worcester'),
 ('Reqchptugcc', 'Sqxmout', 'ND', 'Santa Clarita'),
 ('Nlwulch', 'Fndwhp', 'RI', 'Reno'),
 ('Xcuoig', 'Bunitpkmimwyi', 'IL', 'Santa Rosa'),
 ('Fvgytnqpcyqyz', 'Obpnmaulmruqn', 'CA', 'Amarillo'),
 ('Qanjzy', 'Cvwszrggltdb', 'AS', 'Mobile'),
 ('Sphit', 'Ygttjvzyjeqm', 'LA', 'Fort Wayne'),
 ('Kogbxiowx', 'Cggvhgodl', 'MP', 'Huntsville'),
 ('Azvpcn', 'Sfxwd', 'OK', 'Raleigh'),
 ('Cp', 'Ajfnrdvicjvcr', 'WV', 'Tucson'),
 ('Ccu', 'Kfrg', 'HI', 'Knoxville'),
 ('Nhiiebcmoh', 'Kku', 'MD', 'Lincoln'),
 ('Peeecjukfhv', 'Iaapdnyaendfh', 'IA', 'Augusta-Richmond County'),
 ('Vlyupehfk', 'Xdhuxr', 'DE', 'Madison'),
 ('Mhtepvjn', 'Ec', 'KY', 'Fayetteville'),
 ('Fogpez', 'Lfibxjo', 'PW', 'Fayetteville'),
 ('Myqbhacgnulnb', 'Hborw', 'RI', 'Fayetteville'),
 ('Sg', 'Ttikbfalcmxq', 'NM', 'Chula Vista'),
 ('Ulfuwodyd', 'Cvnq', 'LA', 'Colorado Springs'),
 ('Lnrnyob', 'Yzgtewrepb', 'OK', 'Tacoma'),
 ('Cmzruabgkrb', 'Bunlrzmzwejjt', 'NV', 'Yonkers'),
 ('Vvkv', 'Lrtdwcafeob', 'AS', 'Washington'),
 ('Zqasdw', 'Dqxxgzoe', 'OH', 'Memphis'),
 ('Bz', 'Ccxnn', 'IL', 'Chesapeake'),
 ('Gljjyhggoq', 'Wpvnsjf', 'PW', 'Nashville-Davidson'),
 ('Hrgeneihdaykg', 'Uzhzuskmos', 'CT', 'New Orleans'),
 ('Ovoyp', 'Axmrq', 'MS', 'Anchorage'),
 ('Sryflbzlimrxd', 'Bpvchcptxjiug', 'AL', 'New York'),
 ('Yg', 'Cfnamvxxe', 'PW', 'San Bernardino'),
 ('Tzhoxxtrealxg', 'Xigqiuvztrepl', 'MI', 'Grand Prairie'),
 ('Iq', 'Hrsa', 'OK', 'Houston'),
 ('Okfgsnhqr', 'Alzu', 'NJ', 'Shreveport'),
 ('Wfdtiuvae', 'Xuyhgbvjoc', 'NH', 'Honolulu'),
 ('Jjsbv', 'Ipw', 'GA', 'Henderson'),
 ('Izx', 'Xv', 'AZ', 'Fort Worth'),
 ('Opeckqjbwol', 'Rsaxckainhl', 'DE', 'Yonkers'),
 ('Oqn', 'Yzqp', 'WV', 'New Orleans'),
 ('Iq', 'Vxcoqxi', 'LA', 'Lincoln'),
 ('Zozdj', 'Qgfkxeud', 'SC', 'Aurora'),
 ('Ajfdbsmrzgunc', 'Mdvkojopskcxm', 'LA', 'Greensboro'),
 ('Tpvzk', 'Omsmiguoma', 'NV', 'Colorado Springs'),
 ('Bh', 'Yaetqfgqku', 'PR', 'Huntington Beach'),
 ('Lvq', 'Yaqibvaih', 'GA', 'Birmingham'),
 ('Sb', 'Qdqinmku', 'PW', 'Buffalo'),
 ('Av', 'Xnok', 'IA', 'El Paso'),
 ('Futvgs', 'Cebdd', 'VI', 'Oklahoma City'),
 ('Mtunei', 'Dprpfv', 'NC', 'Laredo'),
 ('Bzevbvkc', 'Batoosz', 'RI', 'Garland'),
 ('Nsbrqwyn', 'Taieghpgxg', 'MN', 'Portland');